### ISSUE TITLE
Не работает генерация второго и последующих вопросов в попытке

### ISSUE THREAD

**Issue by procudin** [CompPrehension/CompPrehension#100]
начать попытку -> сгенерировать следующий вопрос -> вылетает ошибка

https://compprehension.app/basic/pages/exercise?exerciseId=10

**Comment by den1s0v** [comment]
Quick fix of crash: add PR #101

**Comment by den1s0v** [comment]
Возможно, нужно перепроверить подправленную логику в Strategy
