### ISSUE TITLE
Генерация продолжения ответа 

### ISSUE THREAD

**Issue by procudin** [CompPrehension/CompPrehension#49]
Я только начал разбираться с этой частью кода и, судя по реализации, там не учитываются предыдущие ответы студента

https://github.com/procudin/CompPrehension/blob/47dbcd389deaff07288aa6f880251188c30faf38/src/main/java/org/vstu/compprehension/models/businesslogic/domains/ProgrammingLanguageExpressionDomain.java#L585-L601

Ответы студента можно брать из последней успешной интерации (с нулевым количеством ошибок). Сейчас интеракции уже нормально работают.

**Comment by oasychev** [comment]
Там не столько продолжение ответа студента - сколько генерация полностью работающего примера с нуля по шагам.

Хотя можно и за студентом продолжить, но это следующий этап. Сначала нужно worked example.

Пример делал Никита - Никита, просьба теперь посмотреть интеракции и доделать чтобы работало между шагами - и сделать тест на 2-3 шага по очереди.

**Comment by ShadowGorn** [comment]
Сделал, сделал тест, влил

**Comment by ShadowGorn** [comment]
Я возможно неправильно пользуюсь интеракциями, посмотри пожалуйста
