### ISSUE TITLE
Некорректное сохранение последней правильной интеракции

### ISSUE THREAD

**Issue by procudin** [CompPrehension/CompPrehension#52]
Интеракция считается корректной при непустом ```InterpretSentenceResult.correctlyAppliedLaws```, возвращаемым методом ```judgeQuestion```. 
https://github.com/CompPrehension/CompPrehension/blob/b993de8b61abc5620a60d8192f12c6617a427db7/src/main/java/org/vstu/compprehension/controllers/BasicExerciseController.java#L89-L92

Это работает для всех случаев, но для завершающей корректной интерации ```judgeQuestion``` возращает пустой список ```correctlyAppliedLaws```. Из-за этого эта интеракция не учитывается как корректная.

**Comment by oasychev** [comment]
Добавляю Никиту т.к. тестируется на его домене. Никита, проверьте - ваш домен нормально возвращает последний правильно примененный закон?

**Comment by ShadowGorn** [comment]
Да, посмотрю

**Comment by ShadowGorn** [comment]
Что мы тут ожидаем?
CorrectlyAppliedLaws = негативные правила, которые могли произойти на этом шаге. На последнем шаге он ничего не мог нарушить - вот и список пустой.

**Comment by ShadowGorn** [comment]
Как корректную стоит рассматривать интеграцию без ошибок

**Comment by procudin** [comment]
ок, тогда закрываю

**Comment by oasychev** [comment]
Значит надо таки сделать в интеракции флаг о котором мы говорили на последнем совещании - что эта интеракция подсказка правильного решения и от студента не зависела.

Вот в ситуации Никиты я вообще думаю - когда у нас остается всего одна кнопка, надо ли заставлять студента ее нажимать? Если перечень элементов которые надо упорядочить полностью известен (пропускать нельзя, использовать несколько раз нельзя) то последняя интеракция очевидна. Может ее вообще не записывать? Или автоматом генерировать?
