### ISSUE TITLE
Не генерирует правильный ответ для нового вопроса

### ISSUE THREAD

**Issue by procudin** [CompPrehension/CompPrehension#59]
Если создать новый вопрос, и, ничего до этого не нажимая, нажать на кнопку "Next answer", то правильный ответ не сгенерируется. При этом, если совершить какую-то интеракцию (даже некорректную), то генерация будет работать

**Comment by ShadowGorn** [comment]
Кажется тут что-то не так у тебя, в тестах-то работает.

**Comment by ShadowGorn** [comment]
Нашел баг, домен не может найти правильный ответ, если его не вычислил бекенд.
Поменял порядок и поставил assert на это.
